name: Deploy to GitHub Pages

on:
  push:
    branches: [ dev ]

permissions:
  contents: read
  pages: write

jobs:

  build:
    runs-on: ubuntu-24.04
    steps:
    #- name: Setup the job
    #  uses: actions/checkout@v4
    #- name: Pull
    #  run: "echo Job: ${{ github.job }}"
    #- name: Checkout
    #  run: "echo Job: ${{ github.job }}"
    #- name: Build with dotnet
    #  run: "echo Job: ${{ github.job }}"
    #- name: Upload artifact
    #  run: "echo Job: ${{ github.job }}"
    #- name: Post checkout
    #  run: "echo Job: ${{ github.job }}"
    #- name: Complete job
    #  run: "echo Job: ${{ github.job }}"

    - name: Checkout repository
      uses: actions/checkout@v4
  
    - name: Setup WASM tools
      uses: bytecodealliance/actions/wasm-tools/setup@v1
  
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v4
      with:
        global-json-file: global.json

    - name: Restore dependencies
      run: dotnet restore

    - name: Setup libman
      run: |
        dotnet tool install --global microsoft.web.librarymanager.cli
        libman restore

    - name: Build
      run: dotnet build --no-restore

    - name: Publish .NET Core Project
      run: dotnet publish GitHubPages.csproj -c Release -o release --nologo -r linux-x64 -p:PublishTrimmed=true --no-restore --no-build
      working-directory: GitHubPages

    - name: Upload artifacts
      uses: actions/upload-pages-artifact@v3
      with:
        path: GitHubPages/release/

  report-build-status:
    runs-on: ubuntu-24.04
    needs: build
    steps:
    #- name: Setup the job
    - name: Report build status
      run: "echo Job: ${{ github.job }}"
      # run gh api -X POST "repos/$GITHUB_REPOSITORY/pages/telemetry" \
      #       -F github_run_id="$GITHUB_RUN_ID" \
      #       -F conclusion="$CONCLUSION
    #- name: Complete job
  
  deploy:
    runs-on: ubuntu-24.04
    needs: build
    steps:
    #- name: Setup the job
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    #- name: Complete the job
